#Tomcat 设置最大线程，最小备用线程，端口，请求地址  localhost:8005
server:
  tomcat:
    max-threads: 100
    min-spare-threads: 10
  port: 8005
#遇到相同名字是否允许覆盖注册
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: SpringCloud-consul-feign
  #redis服务器地址配置
  redis:
    host: 192.168.1.130
    port: 6379