#Tomcat 设置最大线程，最小备用线程，端口，请求地址  localhost:8004
server:
  tomcat:
    max-threads: 100
    min-spare-threads: 10
  port: 8004
#遇到相同名字是否允许覆盖注册
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: SpringCloud-consul-authorization-manager
  #redis服务器地址配置
  redis:
    host: 192.168.1.130
    port: 6379
#swagger 配置
swagger:
  is:
    enable: true #是否开启swagger
  auth:
    server: http://192.168.3.14:8001/auth/oauth/token   #验证token请求地址：ip+网关+服务名称+请求地址
  service:
    name: manager